# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: zwt_sales_development
  pool: 5
  username: root
  password: this.admin
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: zwt_sales_test
  pool: 5
  username: root
  password: this.admin
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: zwt_sales_production
  pool: 5
  host: localhost
  port: 3306